name: Generate Snake Animation

on:
  schedule:
    # Executa a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # O seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }}

          # Lista de arquivos a serem gerados. Um por linha.
          # Com opções de customização.
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
